# Generated by Django 5.0.1 on 2024-01-20 19:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheetItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Наименование")),
                (
                    "direction",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Приход/расход"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья баланса",
                "verbose_name_plural": "Статьи баланса",
                "db_table": "balance_sheet_items",
            },
        ),
        migrations.CreateModel(
            name="FinancialReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("period_begin", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель отчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовый отчет",
                "verbose_name_plural": "Финансовые отчеты",
                "db_table": "financial_reports",
            },
        ),
        migrations.CreateModel(
            name="AccountingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date(2024, 1, 20),
                        verbose_name="На дату",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(blank=True, default=0, verbose_name="Сумма"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "balance_sheet_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.balancesheetitems",
                        verbose_name="Статья",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="reports.financialreports",
                        verbose_name="Финанмовый отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проводка",
                "verbose_name_plural": "Проводки",
                "db_table": "accounting_transactions",
            },
        ),
    ]
