# Generated by Django 5.0.1 on 2024-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreports",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Заблокирован"),
        ),
    ]
