# Generated by Django 5.0.1 on 2024-06-10 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_financialreports_is_confirmed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreports",
            name="month",
            field=models.IntegerField(default=None, verbose_name="Месяц"),
        ),
        migrations.AddField(
            model_name="financialreports",
            name="year",
            field=models.IntegerField(default=None, verbose_name="Год"),
        ),
        migrations.RemoveField(
            model_name="financialreports",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="financialreports",
            name="period_begin",
        ),
        migrations.RemoveField(
            model_name="financialreports",
            name="period_end",
        ),
        migrations.AlterUniqueTogether(
            name="financialreports",
            unique_together={("month", "year", "author")},
        ),
    ]
