# Generated by Django 5.0.1 on 2024-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_alter_financialreports_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreports",
            name="balance_on_begin",
            field=models.FloatField(default=0, verbose_name="Остаток на начало периода"),
        ),
        migrations.AddField(
            model_name="financialreports",
            name="balance_on_end",
            field=models.FloatField(default=0, verbose_name="Остаток на конец периода"),
        ),
        migrations.AddField(
            model_name="financialreports",
            name="total_in",
            field=models.FloatField(default=0, verbose_name="Приход"),
        ),
        migrations.AddField(
            model_name="financialreports",
            name="total_out",
            field=models.FloatField(default=0, verbose_name="Расход"),
        ),
    ]
