# Generated by Django 5.0.1 on 2024-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_financialreports_balance_on_begin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreports",
            name="in_accounting",
            field=models.BooleanField(default=False, verbose_name="В бухгалтерии"),
        ),
    ]
