# Generated by Django 5.0.1 on 2024-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_rename_in_accounting_financialreports_is_accounted"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingtransactions",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="Подтверждена"),
        ),
    ]
