# Generated by Django 5.0.1 on 2024-06-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_itemslimits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialreports",
            name="month",
            field=models.PositiveSmallIntegerField(default=None, verbose_name="Месяц"),
        ),
        migrations.AlterField(
            model_name="financialreports",
            name="year",
            field=models.PositiveSmallIntegerField(default=None, verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="itemslimits",
            name="month",
            field=models.PositiveSmallIntegerField(default=None, verbose_name="Месяц"),
        ),
        migrations.AlterField(
            model_name="itemslimits",
            name="year",
            field=models.PositiveSmallIntegerField(default=None, verbose_name="Год"),
        ),
    ]
