# Generated by Django 5.0.1 on 2024-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0011_alter_financialreports_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemslimits",
            name="comment",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
