# Generated by Django 5.0.1 on 2024-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_itemslimits_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheetitems",
            name="direction",
            field=models.BooleanField(blank=True, default=False, verbose_name="Приход"),
        ),
    ]
