# Generated by Django 5.0.1 on 2024-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0013_alter_balancesheetitems_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingtransactions",
            name="is_accounting_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Подтверждено бухгалтерией"
            ),
        ),
    ]
