# Generated by Django 5.0.1 on 2024-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0014_accountingtransactions_is_accounting_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingtransactions",
            name="accounting_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий бухгалтера"
            ),
        ),
    ]
