version: '3'
services:
  postgres:
    container_name: postgres-farm-tech-db
    image: postgres:15-alpine
    env_file:
      - dev.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chat}
    ports:
      - "5432:5432"
    networks:
      - local_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis-farm-tech-cache
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-change}
    ports:
      - "6379:6379"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge