# Generated by Django 5.0.1 on 2024-02-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0002_invites_user_alter_invites_email"),
        ("users", "0002_alter_departments_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="invites",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites_for_department",
                to="users.departments",
                verbose_name="Отдел",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites_for_job",
                to="users.jobs",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="on_date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата начала периода работы",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="region",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, verbose_name="Регион"
            ),
        ),
    ]
