# Generated by Django 5.0.1 on 2024-02-15 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0003_invites_department_invites_job_invites_on_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invites",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Начальник",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
