# Generated by Django 5.0.1 on 2024-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0004_invites_manager_invites_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="invites",
            name="address_1",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Адрес для отправки пром материалов",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="address_2",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Адресс для отправки СДЭК",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="city",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="comment_1",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Информации о необходимости выдачи корпоративное авто или компенсации расходов на содержание и амортизацию личного автомобиля",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="employment_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Дата приема на работу"
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="prev_eployee_fio",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="ФИО предыдущего сотрудника",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="promotion_direction",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Направление продвижения",
            ),
        ),
    ]
