# Generated by Django 5.0.1 on 2024-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0005_invites_address_1_invites_address_2_invites_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invites",
            name="first_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="is_verified_by_accounts",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Согласовано бухгалтерией",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="is_verified_by_hr",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Согласовано кадрами"
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="last_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Отчество",
            ),
        ),
        migrations.AddField(
            model_name="invites",
            name="photo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="", verbose_name="Фото"
            ),
        ),
    ]
