# Generated by Django 5.0.1 on 2024-09-19 07:13

import django.db.models.deletion
from django.db import migrations, models


def clear_region_field(apps, schema_editor):
    Invites = apps.get_model("auth2", "Invites")
    Invites.objects.update(region=None)


class Migration(migrations.Migration):
    dependencies = [
        ("auth2", "0006_invites_first_name_invites_is_verified_by_accounts_and_more"),
        ("users", "0009_user_employment_date"),
    ]

    operations = [
        migrations.RunPython(clear_region_field),

        migrations.AlterField(
            model_name="invites",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="invites/photos",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="invites",
            name="region",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites_in",
                to="users.regions",
                verbose_name="Регион",
            ),
        ),
    ]
