# Generated by Django 5.0.1 on 2024-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trademarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Словесное описание",
                    ),
                ),
                (
                    "mktu_cls",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Классы МКТУ",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Номер заявки",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Номер регистрации",
                    ),
                ),
                (
                    "owner",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Владелец"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Действует"), ("inactive", "Не действует")],
                        default="active",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Действует до"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товарный знак",
                "verbose_name_plural": "Товарные знаки",
                "db_table": "trademarks",
            },
        ),
    ]
