# Generated by Django 5.0.1 on 2024-01-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="job",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Отчетство",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=25, null=True, verbose_name="Телефон"
            ),
        ),
    ]
