# Generated by Django 5.0.1 on 2024-01-19 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="staff",
            field=models.ManyToManyField(
                blank=True,
                related_name="department",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудники",
            ),
        ),
    ]
