# Generated by Django 5.0.1 on 2024-01-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_departments_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, unique=True, verbose_name="Название"
            ),
        ),
    ]
