# Generated by Django 5.0.1 on 2024-01-13 08:21

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_job_user_middle_name_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="job",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, verbose_name="Job"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=25, null=True, verbose_name="Phone"
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Department"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.AddField(
            model_name="users",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.department",
                verbose_name="Department",
            ),
        ),
    ]
