# Generated by Django 5.0.1 on 2024-01-13 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_job_alter_user_phone_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "db_table": "jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Отдел", "verbose_name_plural": "Отделы"},
        ),
        migrations.RemoveField(
            model_name="users",
            name="department",
        ),
        migrations.AddField(
            model_name="department",
            name="staff",
            field=models.ManyToManyField(
                related_name="department",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудники",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=25, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.job",
                verbose_name="Должность",
            ),
        ),
    ]
