# Generated by Django 5.0.1 on 2024-04-23 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_status_user_vice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="vice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whose_vice",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заместитель",
            ),
        ),
    ]
