# Generated by Django 5.0.1 on 2024-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_is_region_manager_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employment_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Дата приема на работу"
            ),
        ),
    ]
