# Generated by Django 5.0.1 on 2024-11-13 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_employment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_1",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Адрес для отправки пром материалов",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_2",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Адресс для отправки СДЭК",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="comment_1",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Информации о необходимости выдачи корпоративное авто или компенсации расходов на содержание и амортизацию личного автомобиля",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="who_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Начальник",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="on_date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата начала периода работы",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="prev_eployee_fio",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="ФИО предыдущего сотрудника",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promotion_direction",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Направление продвижения",
            ),
        ),
    ]
