# Generated by Django 5.0.1 on 2024-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_notificationsrecipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsrecipients",
            name="label",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
    ]
