# Generated by Django 5.0.1 on 2024-12-06 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_notificationsrecipients_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
