# Generated by Django 5.0.1 on 2024-01-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                ("kind", models.CharField(max_length=50, verbose_name="Вид заявки")),
                (
                    "sub_kind",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Тип заявки",
                    ),
                ),
                ("date_begin", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrdersFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="files/orders/", verbose_name="Файл"),
                ),
            ],
            options={
                "verbose_name": "Файлы заявки",
                "verbose_name_plural": "Файлы заявок",
                "db_table": "orders_files",
            },
        ),
    ]
