# Generated by Django 5.0.1 on 2024-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersfiles",
            name="file",
            field=models.FileField(upload_to="files/orders/", verbose_name="Файл"),
        ),
    ]
