# Generated by Django 5.0.1 on 2024-02-07 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRoomsReservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_begin", models.DateTimeField(verbose_name="Дата начала брони")),
                ("date_end", models.DateTimeField(verbose_name="Дата окончания брони")),
                (
                    "is_confirmed",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Подтверждено"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_rooms_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто забронировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь переговорной",
                "verbose_name_plural": "Брони переговорной",
                "db_table": "meeting_rooms_reservations",
            },
        ),
    ]
