# Generated by Django 5.0.1 on 2024-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingroomsreservations",
            name="name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Название",
            ),
        ),
    ]
