# Generated by Django 5.0.1 on 2024-02-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_meetingroomsreservations_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Переговорная",
                "verbose_name_plural": "Переговорные",
                "db_table": "meeting_rooms",
            },
        ),
        migrations.RemoveField(
            model_name="meetingroomsreservations",
            name="name",
        ),
        migrations.AddField(
            model_name="meetingroomsreservations",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="meetings.meetingrooms",
                verbose_name="Переговорная",
            ),
            preserve_default=False,
        ),
    ]
